### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by le2Ks** [arcadiablock/assets#1]
Hi, is there any discord group for your project? Ty

**Comment by arcadiablock** [comment]
> Hi, is there any discord group for your project? Ty

Hello Tyler! Nice to meet you.

Thanks for your interest in our project! 

We're building Discord right now, so it's private. I want to tell you when it's released, can you contact me via telegram? @Arcadia_team

**Comment by le2Ks** [comment]
Hello, okk contacted you on Telegram ty!
